# Scratchpad : 
## row data to tabular data with complete timestamps
### Now with timestamps as data :) 



In [119]:
import pandas as pd
import numpy as np
import time

In [120]:
# parameters

# start_time = "2018-12-31 21:58:42"
end_time = "2019-01-01 11:58:42"
# generate this please
start_time = "?????"

time_frequency_for_periods__for_basic_data = "5T"
num_of_time_periods___for_basic_data = 24*20 # 24 hrs * 12 x 5 mins in each hour

# when generating time periods 
sampling_frequency = "3T"



# --- data urls 

curr_url = "????"
nordic_midnight_24_hrs_data__url = "/Users/miska/Documents/open_something/luftdaten/luftdaten_code/luftdaten__make_tabular_data__from_db_data/ld_NYE_midnight_24hrs_nordics_all_data_01.csv"

# set the current data source 
curr_url =nordic_midnight_24_hrs_data__url

In [121]:
#open data 

in_data = pd.read_csv( curr_url )
in_data.shape

(127109, 7)

In [122]:
# make sure the timestamps are timestamps
in_data['timestamp'] = pd.to_datetime( in_data['timestamp'] ) 

In [123]:
in_data = in_data.sort_values( by=['timestamp'] )

In [124]:
type( in_data['timestamp'][0] )

pandas._libs.tslibs.timestamps.Timestamp

In [125]:
# quick datadump
in_data[:15]

sensor_id sensor_namee     lat     lon           timestamp      p1     p2
78       13012       SDS011  57.662  12.006 2018-12-31 11:55:19    6.30   2.60
158      18112       SDS011  57.478  11.978 2018-12-31 11:56:37  174.80  15.13
116      15067       SDS011  60.024  18.770 2018-12-31 11:56:38    1.62   1.02
47       11765       SDS011  55.716  13.244 2018-12-31 11:56:39   33.95  13.40
110      14811       SDS011  57.706  11.900 2018-12-31 11:56:40   63.25  10.33
22       10827       SDS011  59.334  13.512 2018-12-31 11:56:40   11.45   6.00
147      17538       SDS011  55.612  12.972 2018-12-31 11:56:40   13.68   3.12
3         7406       SDS011  56.964  24.128 2018-12-31 11:56:41   11.05   6.62
128      16155       SDS011  59.832  17.632 2018-12-31 11:56:42    1.66   1.10
31       11058       SDS011  59.272  15.220 2018-12-31 11:56:43    2.99   1.46
133      16533       SDS011  55.722  13.202 2018-12-31 11:56:43   26.43  14.00
108      14807       SDS011  57.718  12.034 2018-12-31 11:56:43   55.02   8.75
26       10924       SDS011  59.860  17.652 2018-12-31 11:56:44    2.58   1.16
18       10723       SDS011  59.298  18.052 2018-12-31 11:56:45    4.90   2.76
153      17923       SDS011  55.730  13.200 2018-12-31 11:56:47   42.12  18.17

In [126]:
# now the time has been sorted, turn it into epoch time :) 

In [127]:
unique_sensor_ids = in_data['sensor_id'].unique()
unique_sensor_ids.shape

(205,)

In [128]:
type( unique_sensor_ids )

numpy.ndarray

In [129]:
unique_sensor_ids = np.sort( unique_sensor_ids )

In [130]:
unique_sensor_ids

array([ 5321,  7273,  7275,  7277,  7406,  7426,  7428,  7469,  7499,
        7597,  8683,  9344,  9368,  9411,  9436,  9743,  9797, 10216,
       10234, 10250, 10281, 10430, 10588, 10647, 10719, 10721, 10723,
       10803, 10823, 10825, 10827, 10843, 10914, 10922, 10924, 10926,
       11002, 11004, 11006, 11058, 11060, 11232, 11374, 11376, 11378,
       11380, 11384, 11402, 11404, 11445, 11543, 11546, 11548, 11550,
       11552, 11554, 11657, 11659, 11661, 11663, 11763, 11765, 11767,
       11769, 11771, 11773, 12120, 12122, 12124, 12127, 12129, 12131,
       12133, 12135, 12137, 12141, 12381, 12383, 12385, 12387, 12389,
       12391, 12393, 12663, 12673, 12675, 12679, 12681, 12687, 12691,
       12693, 12861, 12990, 12994, 13000, 13010, 13012, 13014, 13018,
       13020, 13307, 13419, 13421, 13423, 13425, 13428, 13441, 13443,
       13475, 13477, 13479, 13483, 13762, 14017, 14133, 14209, 14264,
       14276, 14278, 14282, 14284, 14288, 14290, 14292, 14294, 14296,
       14300, 14722,

In [135]:
random_sensor_id_data = in_data[ in_data['sensor_id'] == unique_sensor_ids[1] ]
random_sensor_id_data.shape

(716, 7)

In [136]:
random_sensor_id_data

sensor_id sensor_namee     lat     lon           timestamp    p1    p2
0           7273       SDS011  60.002  17.846 2018-12-31 11:57:22  3.43  1.56
175         7273       SDS011  60.002  17.846 2018-12-31 11:59:50  3.78  1.55
44754       7273       SDS011  60.002  17.846 2018-12-31 12:04:47  4.12  1.90
44833       7273       SDS011  60.002  17.846 2018-12-31 12:07:16  3.45  1.75
42851       7273       SDS011  60.002  17.846 2018-12-31 12:09:44  2.10  1.36
45041       7273       SDS011  60.002  17.846 2018-12-31 12:12:13  1.45  1.16
43013       7273       SDS011  60.002  17.846 2018-12-31 12:14:43  2.02  1.28
45230       7273       SDS011  60.002  17.846 2018-12-31 12:19:43  1.78  1.36
43186       7273       SDS011  60.002  17.846 2018-12-31 12:22:12  2.00  1.36
43267       7273       SDS011  60.002  17.846 2018-12-31 12:24:40  2.45  1.42
43426       7273       SDS011  60.002  17.846 2018-12-31 12:27:09  2.58  1.55
43345       7273       SDS011  60.002  17.846 2018-12-31 12:27:09  2.58  1.55
43699       7273       SDS011  60.002  17.846 2018-12-31 12:29:37  3.67  1.80
45593       7273       SDS011  60.002  17.846 2018-12-31 12:29:37  3.67  1.80
43874       7273       SDS011  60.002  17.846 2018-12-31 12:34:35  2.30  1.88
44049       7273       SDS011  60.002  17.846 2018-12-31 12:37:03  2.80  1.84
44224       7273       SDS011  60.002  17.846 2018-12-31 12:39:32  2.74  1.75
44401       7273       SDS011  60.002  17.846 2018-12-31 12:42:00  3.00  1.80
44579       7273       SDS011  60.002  17.846 2018-12-31 12:46:57  2.95  1.83
47741       7273       SDS011  60.002  17.846 2018-12-31 12:49:26  2.46  1.75
47825       7273       SDS011  60.002  17.846 2018-12-31 12:51:54  3.20  1.60
47910       7273       SDS011  60.002  17.846 2018-12-31 12:54:23  3.28  1.50
47987       7273       SDS011  60.002  17.846 2018-12-31 12:56:51  2.14  1.46
46035       7273       SDS011  60.002  17.846 2018-12-31 13:01:48  2.35  1.42
46124       7273       SDS011  60.002  17.846 2018-12-31 13:04:17  2.25  1.28
46199       7273       SDS011  60.002  17.846 2018-12-31 13:06:45  2.50  1.36
48357       7273       SDS011  60.002  17.846 2018-12-31 13:09:14  2.04  1.45
46374       7273       SDS011  60.002  17.846 2018-12-31 13:11:42  2.11  1.40
48517       7273       SDS011  60.002  17.846 2018-12-31 13:16:47  2.25  1.62
46578       7273       SDS011  60.002  17.846 2018-12-31 13:19:17  2.22  1.64
...          ...          ...     ...     ...                 ...   ...   ...
36287       7273       SDS011  60.002  17.846 2019-01-01 22:31:21  1.64  1.28
36463       7273       SDS011  60.002  17.846 2019-01-01 22:33:55  1.60  1.20
36639       7273       SDS011  60.002  17.846 2019-01-01 22:36:26  2.43  1.32
36814       7273       SDS011  60.002  17.846 2019-01-01 22:38:57  3.85  1.52
36987       7273       SDS011  60.002  17.846 2019-01-01 22:41:30  4.04  1.35
37162       7273       SDS011  60.002  17.846 2019-01-01 22:46:33  2.55  1.38
37340       7273       SDS011  60.002  17.846 2019-01-01 22:49:03  2.88  1.45
37520       7273       SDS011  60.002  17.846 2019-01-01 22:51:32  3.55  1.45
37697       7273       SDS011  60.002  17.846 2019-01-01 22:54:00  4.05  1.35
37874       7273       SDS011  60.002  17.846 2019-01-01 22:56:29  3.56  1.35
38050       7273       SDS011  60.002  17.846 2019-01-01 23:01:27  3.62  1.25
38225       7273       SDS011  60.002  17.846 2019-01-01 23:04:04  3.12  1.18
38398       7273       SDS011  60.002  17.846 2019-01-01 23:06:38  2.93  1.34
38575       7273       SDS011  60.002  17.846 2019-01-01 23:09:07  3.57  1.30
41889       7273       SDS011  60.002  17.846 2019-01-01 23:11:35  3.18  1.14
39642       7273       SDS011  60.002  17.846 2019-01-01 23:16:32  4.22  1.28
42066       7273       SDS011  60.002  17.846 2019-01-01 23:19:04  3.28  1.23
39829       7273       SDS011  60.002  17.846 2019-01-01 23:21:36  3.64  1.45
39915       7273       SDS011  60.002  17.846 2019-01-01 23:24:05  3.66  1.56
39989       7273       SDS011

In [137]:
# make sure the timestamp column is a timestamp column
random_sensor_id_data['timestamp'] = pd.to_datetime( random_sensor_id_data['timestamp'] )

/Applications/z_extras/code/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [138]:
random_sensor_id_data['timestamp']

0       2018-12-31 11:57:22
175     2018-12-31 11:59:50
44754   2018-12-31 12:04:47
44833   2018-12-31 12:07:16
42851   2018-12-31 12:09:44
45041   2018-12-31 12:12:13
43013   2018-12-31 12:14:43
45230   2018-12-31 12:19:43
43186   2018-12-31 12:22:12
43267   2018-12-31 12:24:40
43426   2018-12-31 12:27:09
43345   2018-12-31 12:27:09
43699   2018-12-31 12:29:37
45593   2018-12-31 12:29:37
43874   2018-12-31 12:34:35
44049   2018-12-31 12:37:03
44224   2018-12-31 12:39:32
44401   2018-12-31 12:42:00
44579   2018-12-31 12:46:57
47741   2018-12-31 12:49:26
47825   2018-12-31 12:51:54
47910   2018-12-31 12:54:23
47987   2018-12-31 12:56:51
46035   2018-12-31 13:01:48
46124   2018-12-31 13:04:17
46199   2018-12-31 13:06:45
48357   2018-12-31 13:09:14
46374   2018-12-31 13:11:42
48517   2018-12-31 13:16:47
46578   2018-12-31 13:19:17
                ...        
36287   2019-01-01 22:31:21
36463   2019-01-01 22:33:55
36639   2019-01-01 22:36:26
36814   2019-01-01 22:38:57
36987   2019-01-01 2

In [139]:
type( random_sensor_id_data['timestamp'].iloc[0] )

pandas._libs.tslibs.timestamps.Timestamp

In [140]:
random_sensor_id_data[ random_sensor_id_data['p1'] == 3.45 ]

sensor_id sensor_namee     lat     lon           timestamp    p1    p2
44833       7273       SDS011  60.002  17.846 2018-12-31 12:07:16  3.45  1.75

In [141]:
%time random_sensor_id_data__sorted_by_time = random_sensor_id_data.sort_values( by=['timestamp'] )

CPU times: user 1.33 ms, sys: 1.26 ms, total: 2.59 ms
Wall time: 1.42 ms


In [142]:
np.arange( 10 )

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [143]:
one = np.array( np.arange(10) )

In [144]:
one[0]

0

In [145]:
type( one[0] )

numpy.int64

#### checking out changing the size of arrays - eg here with pad(ding)

In [146]:
np.pad( one, (0,4), 'edge')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 9, 9, 9])

In [147]:
np.pad( one, (0,4), 'constant', constant_values=(-1))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, -1, -1, -1, -1])

#### trying to insert list items in numpy arrays

In [148]:
list_ = range( 10 )

In [149]:
list_

range(0, 10)

In [150]:
np_array = np.array( list_ ) 

In [151]:
type( np_array[0] ) 

numpy.int64

In [152]:
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [153]:
# test print
in_data[:10]

sensor_id sensor_namee     lat     lon           timestamp      p1     p2
78       13012       SDS011  57.662  12.006 2018-12-31 11:55:19    6.30   2.60
158      18112       SDS011  57.478  11.978 2018-12-31 11:56:37  174.80  15.13
116      15067       SDS011  60.024  18.770 2018-12-31 11:56:38    1.62   1.02
47       11765       SDS011  55.716  13.244 2018-12-31 11:56:39   33.95  13.40
110      14811       SDS011  57.706  11.900 2018-12-31 11:56:40   63.25  10.33
22       10827       SDS011  59.334  13.512 2018-12-31 11:56:40   11.45   6.00
147      17538       SDS011  55.612  12.972 2018-12-31 11:56:40   13.68   3.12
3         7406       SDS011  56.964  24.128 2018-12-31 11:56:41   11.05   6.62
128      16155       SDS011  59.832  17.632 2018-12-31 11:56:42    1.66   1.10
31       11058       SDS011  59.272  15.220 2018-12-31 11:56:43    2.99   1.46

#### trying to make a multi-dimensional np_array

In [154]:
unique_sensor_ids

array([ 5321,  7273,  7275,  7277,  7406,  7426,  7428,  7469,  7499,
        7597,  8683,  9344,  9368,  9411,  9436,  9743,  9797, 10216,
       10234, 10250, 10281, 10430, 10588, 10647, 10719, 10721, 10723,
       10803, 10823, 10825, 10827, 10843, 10914, 10922, 10924, 10926,
       11002, 11004, 11006, 11058, 11060, 11232, 11374, 11376, 11378,
       11380, 11384, 11402, 11404, 11445, 11543, 11546, 11548, 11550,
       11552, 11554, 11657, 11659, 11661, 11663, 11763, 11765, 11767,
       11769, 11771, 11773, 12120, 12122, 12124, 12127, 12129, 12131,
       12133, 12135, 12137, 12141, 12381, 12383, 12385, 12387, 12389,
       12391, 12393, 12663, 12673, 12675, 12679, 12681, 12687, 12691,
       12693, 12861, 12990, 12994, 13000, 13010, 13012, 13014, 13018,
       13020, 13307, 13419, 13421, 13423, 13425, 13428, 13441, 13443,
       13475, 13477, 13479, 13483, 13762, 14017, 14133, 14209, 14264,
       14276, 14278, 14282, 14284, 14288, 14290, 14292, 14294, 14296,
       14300, 14722,

In [155]:
num_of_items_per_row = ( np.int(60/3) * 24 ) # number of 3 minute periods in an hour * 24 hour 
num_of_items_per_row

480

In [156]:
array_w_slots_for_all_sensors_and_time_periods_in_the_day = np.zeros( unique_sensor_ids.shape[0] * num_of_items_per_row )

In [157]:
array_w_slots_for_all_sensors_and_time_periods_in_the_day = array_w_slots_for_all_sensors_and_time_periods_in_the_day.reshape( [ unique_sensor_ids.shape[0], num_of_items_per_row  ])

In [158]:
array_w_slots_for_all_sensors_and_time_periods_in_the_day.shape

(205, 480)

In [159]:
array_w_slots_for_all_sensors_and_time_periods_in_the_day[0].shape

(480,)

In [160]:
#### now try fetch all the data from different sensors ids… 

In [161]:
# first, change the indata timestamps into epoch time

In [162]:
in_data.head()

sensor_id sensor_namee     lat     lon           timestamp      p1     p2
78       13012       SDS011  57.662  12.006 2018-12-31 11:55:19    6.30   2.60
158      18112       SDS011  57.478  11.978 2018-12-31 11:56:37  174.80  15.13
116      15067       SDS011  60.024  18.770 2018-12-31 11:56:38    1.62   1.02
47       11765       SDS011  55.716  13.244 2018-12-31 11:56:39   33.95  13.40
110      14811       SDS011  57.706  11.900 2018-12-31 11:56:40   63.25  10.33

In [163]:
in_data.tail()

sensor_id sensor_namee     lat     lon           timestamp    p1    p2
41632      19119       SDS011  56.972  24.132 2019-01-01 23:59:56  2.41  0.96
41612      12129       SDS011  59.340  18.040 2019-01-01 23:59:56  1.85  0.80
41613      12131       SDS011  59.450  17.916 2019-01-01 23:59:56  1.48  0.52
41601      10843       SDS011  59.354  18.364 2019-01-01 23:59:57  7.26  1.60
41603      11374       SDS011  59.258  18.008 2019-01-01 23:59:58  2.65  2.01

In [164]:
# make sure the timestamps column is a timestamps object colunm
in_data['timestamp'] = pd.to_datetime( in_data['timestamp'] )

In [165]:
type( in_data['timestamp'][0] )

pandas._libs.tslibs.timestamps.Timestamp

In [166]:
# turn the timestamps column into epoch time
in_data['timestamp'] = in_data['timestamp'].astype( 'int64' )

In [167]:
# make things a bit smaller
in_data['timestamp'] = in_data['timestamp'] / ( 10**9)

In [168]:
type( in_data['timestamp'][0] )

numpy.float64

In [169]:
time.ctime( in_data['timestamp'][0] ) 

'Mon Dec 31 12:57:22 2018'

In [170]:
# quick check of what in_data looks like … particularly the timestamp
in_data[:10]

sensor_id sensor_namee     lat     lon     timestamp      p1     p2
78       13012       SDS011  57.662  12.006  1.546257e+09    6.30   2.60
158      18112       SDS011  57.478  11.978  1.546257e+09  174.80  15.13
116      15067       SDS011  60.024  18.770  1.546257e+09    1.62   1.02
47       11765       SDS011  55.716  13.244  1.546257e+09   33.95  13.40
110      14811       SDS011  57.706  11.900  1.546257e+09   63.25  10.33
22       10827       SDS011  59.334  13.512  1.546257e+09   11.45   6.00
147      17538       SDS011  55.612  12.972  1.546257e+09   13.68   3.12
3         7406       SDS011  56.964  24.128  1.546257e+09   11.05   6.62
128      16155       SDS011  59.832  17.632  1.546257e+09    1.66   1.10
31       11058       SDS011  59.272  15.220  1.546257e+09    2.99   1.46

In [171]:
#### check the array lengths - do a printout of the data array lengths 
#### f- for each sensor 
#
# of the time series we have from the sensors in the data 

starttime = time.time()

# get all unique sensor ids 
unique_sensor_ids = in_data['sensor_id'].unique()
unique_sensor_ids = np.sort( unique_sensor_ids )

# out list of sensor id data
out_list_of_sensor_ids = []

# array lengths 
array_lengths = []

for curr_sensor_id in unique_sensor_ids:
        
        curr_sensor_data = in_data[ in_data['sensor_id'] == curr_sensor_id ]
        
        curr_array_length = curr_sensor_data.shape[0]
        array_lengths.append( curr_array_length )
        
        print("\n -- working on sensor_id "+str( curr_sensor_id)+" - which has a length of "+str( curr_array_length ) )
        

print("\n ----- and that all took "+str( time.time() - starttime )+" seconds ")
    



 -- working on sensor_id 5321 - which has a length of 2

 -- working on sensor_id 7273 - which has a length of 716

 -- working on sensor_id 7275 - which has a length of 692

 -- working on sensor_id 7277 - which has a length of 721

 -- working on sensor_id 7406 - which has a length of 720

 -- working on sensor_id 7426 - which has a length of 19

 -- working on sensor_id 7428 - which has a length of 721

 -- working on sensor_id 7469 - which has a length of 700

 -- working on sensor_id 7499 - which has a length of 605

 -- working on sensor_id 7597 - which has a length of 721

 -- working on sensor_id 8683 - which has a length of 721

 -- working on sensor_id 9344 - which has a length of 7

 -- working on sensor_id 9368 - which has a length of 407

 -- working on sensor_id 9411 - which has a length of 650

 -- working on sensor_id 9436 - which has a length of 722

 -- working on sensor_id 9743 - which has a length of 498

 -- working on sensor_id 9797 - which has a length of 721

 


 -- working on sensor_id 17351 - which has a length of 720

 -- working on sensor_id 17532 - which has a length of 719

 -- working on sensor_id 17534 - which has a length of 721

 -- working on sensor_id 17536 - which has a length of 719

 -- working on sensor_id 17538 - which has a length of 694

 -- working on sensor_id 17542 - which has a length of 18

 -- working on sensor_id 17576 - which has a length of 722

 -- working on sensor_id 17650 - which has a length of 721

 -- working on sensor_id 17662 - which has a length of 721

 -- working on sensor_id 17710 - which has a length of 721

 -- working on sensor_id 17712 - which has a length of 719

 -- working on sensor_id 17923 - which has a length of 721

 -- working on sensor_id 17925 - which has a length of 722

 -- working on sensor_id 17927 - which has a length of 722

 -- working on sensor_id 18056 - which has a length of 721

 -- working on sensor_id 18110 - which has a length of 722

 -- working on sensor_id 18112 - which h

In [172]:
array_lengths

[2,
 716,
 692,
 721,
 720,
 19,
 721,
 700,
 605,
 721,
 721,
 7,
 407,
 650,
 722,
 498,
 721,
 721,
 324,
 719,
 720,
 721,
 648,
 721,
 714,
 721,
 711,
 721,
 720,
 722,
 700,
 722,
 721,
 721,
 721,
 721,
 722,
 721,
 720,
 721,
 119,
 720,
 716,
 721,
 722,
 699,
 719,
 48,
 720,
 721,
 720,
 720,
 62,
 224,
 357,
 24,
 75,
 45,
 717,
 720,
 722,
 721,
 720,
 722,
 721,
 424,
 721,
 318,
 722,
 660,
 722,
 721,
 397,
 721,
 721,
 721,
 721,
 706,
 659,
 722,
 721,
 718,
 721,
 717,
 720,
 260,
 234,
 2,
 691,
 721,
 709,
 719,
 708,
 720,
 720,
 713,
 706,
 85,
 720,
 640,
 632,
 721,
 721,
 509,
 681,
 721,
 720,
 722,
 720,
 721,
 123,
 720,
 398,
 696,
 698,
 721,
 721,
 721,
 709,
 721,
 45,
 267,
 554,
 721,
 717,
 710,
 472,
 577,
 721,
 721,
 703,
 722,
 721,
 720,
 719,
 721,
 721,
 644,
 720,
 720,
 55,
 721,
 721,
 692,
 719,
 676,
 721,
 720,
 721,
 2,
 640,
 705,
 722,
 346,
 720,
 722,
 696,
 721,
 721,
 336,
 721,
 720,
 721,
 720,
 721,
 6,
 706,
 458,
 721,
 721,

In [173]:
max_num_of_sensings_per_day = np.max( array_lengths ) 
min_num_of_sensings_per_day = np.min( array_lengths ) 

In [174]:
min_num_of_sensings_per_day, max_num_of_sensings_per_day

(2, 722)

In [175]:
unique_sensor_ids[0]

5321

In [176]:
# test what the p1 data looks like for the first sensor
np.array( in_data[ in_data['sensor_id'] == unique_sensor_ids[0] ]['p1'] ) 

array([5.28, 5.28])

In [177]:
# test what the timetamps look like for the last sensor, which has very little data
np.array( in_data[ in_data['sensor_id'] == unique_sensor_ids[-1] ]['timestamp'] )

array([1.54625748e+09, 1.54625763e+09, 1.54625778e+09, 1.54625807e+09,
       1.54625822e+09, 1.54625837e+09, 1.54625852e+09, 1.54625867e+09,
       1.54625896e+09, 1.54625911e+09, 1.54625926e+09, 1.54625926e+09,
       1.54625926e+09, 1.54625942e+09, 1.54625956e+09, 1.54625986e+09,
       1.54626001e+09, 1.54626016e+09, 1.54626030e+09, 1.54626045e+09,
       1.54626075e+09, 1.54626090e+09, 1.54626105e+09, 1.54626121e+09,
       1.54626137e+09, 1.54626153e+09, 1.54626171e+09, 1.54626203e+09,
       1.54626220e+09, 1.54626236e+09, 1.54626252e+09, 1.54626268e+09,
       1.54626268e+09, 1.54626307e+09, 1.54626307e+09, 1.54626343e+09,
       1.54626343e+09, 1.54626396e+09, 1.54626412e+09, 1.54626426e+09,
       1.54626456e+09, 1.54626471e+09, 1.54626486e+09, 1.54626501e+09,
       1.54626515e+09, 1.54626545e+09, 1.54626560e+09, 1.54626575e+09,
       1.54626590e+09, 1.54626604e+09, 1.54626634e+09, 1.54626649e+09,
       1.54626664e+09, 1.54626679e+09, 1.54626693e+09, 1.54626723e+09,
      

#### now try the same with the real numpy out_array … 

In [178]:
# -- first make an array to fit the out values

# prepare variables

sensing_period_lengths_in_min = 3
sensing_period_lengths_in_seconds = sensing_period_lengths_in_min * 60

sensing_periods_in_a_day = int( 60/sensing_period_lengths_in_min ) * 24
sensing_periods_in_a_day




480

In [179]:
sensing_period_lengths_in_seconds

180

In [180]:
type( max_num_of_sensings_per_day ) 

numpy.int64

In [191]:
# get all unique sensor ids 
unique_sensor_ids = in_data['sensor_id'].unique()
unique_sensor_ids = np.sort( unique_sensor_ids )
num_of__unique_sensor_ids = unique_sensor_ids.shape[0]
num_of__unique_sensor_ids

205

In [192]:
# mostly used to store timestamps and their relevant indicies
out_numpy_array_w_all_sensor_values = np.zeros( num_of__unique_sensor_ids * max_num_of_sensings_per_day )

In [193]:
# reshape it to be a nice multidimensional array 
out_numpy_array_w_all_sensor_values = out_numpy_array_w_all_sensor_values.reshape( [ num_of__unique_sensor_ids, max_num_of_sensings_per_day ] )

In [194]:
out_numpy_array_w_all_sensor_values.shape

(205, 722)

In [195]:
# and also make arrays for actual sensor readings / values 

In [196]:
out_numpy_array_w_all_sensor_values_PART_TWO = np.zeros( num_of__unique_sensor_ids * max_num_of_sensings_per_day )

In [197]:
out_numpy_array_w_all_sensor_values_PART_TWO = out_numpy_array_w_all_sensor_values_PART_TWO.reshape( out_numpy_array_w_all_sensor_values.shape )

In [198]:
out_numpy_array_w_all_sensor_values_PART_TWO.shape

(205, 722)

In [199]:
out_numpy_array_w_all_sensor_values

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [200]:
in_data.iloc[:10]

sensor_id sensor_namee     lat     lon     timestamp      p1     p2
78       13012       SDS011  57.662  12.006  1.546257e+09    6.30   2.60
158      18112       SDS011  57.478  11.978  1.546257e+09  174.80  15.13
116      15067       SDS011  60.024  18.770  1.546257e+09    1.62   1.02
47       11765       SDS011  55.716  13.244  1.546257e+09   33.95  13.40
110      14811       SDS011  57.706  11.900  1.546257e+09   63.25  10.33
22       10827       SDS011  59.334  13.512  1.546257e+09   11.45   6.00
147      17538       SDS011  55.612  12.972  1.546257e+09   13.68   3.12
3         7406       SDS011  56.964  24.128  1.546257e+09   11.05   6.62
128      16155       SDS011  59.832  17.632  1.546257e+09    1.66   1.10
31       11058       SDS011  59.272  15.220  1.546257e+09    2.99   1.46

In [201]:
starttime = time.time()

found_minimal_value = 100000000000000000;

# for curr_sensor_id_index in range( unique_sensor_ids.shape[0] ) :
for curr_sensor_id_index in range( 2 ) :
        
        curr_sensor_id_and_row_num_i = unique_sensor_ids[ curr_sensor_id_index ]
        
        # -- fetch the time values 
        curr_sensor_data = in_data[ in_data['sensor_id'] == curr_sensor_id_and_row_num_i ]['timestamp']
        
        # -- find the minimal value in the array and 
        # (below) check if it's the absolutely lowest value
        # in the whole array
        curr_min_value = np.min( curr_sensor_data )
        
        # min check against the whole larger array
        if curr_min_value < found_minimal_value:
            found_minimal_value = curr_min_value
        
        # -- prepare for inserion - find the length of data
        curr_sensor_data_length = curr_sensor_data.shape[0]
        
        print("\n -- working on row "+str( curr_sensor_id_index )+"/"+str( unique_sensor_ids.shape[0] )+" sensor_id "+str( curr_sensor_id_and_row_num_i )+" - which has a length of "+str( curr_sensor_data_length ) )
        
        # -- insert the timestamp data into the larger timestapm numpy array 
        out_numpy_array_w_all_sensor_values[ curr_sensor_id_index ][ 0 : curr_sensor_data_length ] = curr_sensor_data
        
        # --- also inser save some sensor values 
        # fetch the sensor ( p1 ) values 
        curr_sensor_data_pt02 = in_data[  in_data['sensor_id'] == curr_sensor_id_and_row_num_i ]['p1']
        
        # insert the value into the larger sensor data array
        out_numpy_array_w_all_sensor_values_PART_TWO[ curr_sensor_id_index ][ 0 : curr_sensor_data_length ] = curr_sensor_data_pt02
        

print("\n ----- and that all took "+str( time.time() - starttime )+" seconds ")
print(" --------- and the found min value was "+str( found_minimal_value  ) ) 
    


 -- working on row 0/205 sensor_id 5321 - which has a length of 2

 -- working on row 1/205 sensor_id 7273 - which has a length of 716

 ----- and that all took 0.005962848663330078 seconds 
 --------- and the found min value was 1546257442.0


In [202]:
found_minimal_value

1546257442.0

In [204]:
out_numpy_array_w_all_sensor_values[0]

array([1.5463367e+09, 1.5463367e+09, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e

In [205]:
out_numpy_array_w_all_sensor_values[1]

array([1.54625744e+09, 1.54625759e+09, 1.54625789e+09, 1.54625804e+09,
       1.54625818e+09, 1.54625833e+09, 1.54625848e+09, 1.54625878e+09,
       1.54625893e+09, 1.54625908e+09, 1.54625923e+09, 1.54625923e+09,
       1.54625938e+09, 1.54625938e+09, 1.54625968e+09, 1.54625982e+09,
       1.54625997e+09, 1.54626012e+09, 1.54626042e+09, 1.54626057e+09,
       1.54626071e+09, 1.54626086e+09, 1.54626101e+09, 1.54626131e+09,
       1.54626146e+09, 1.54626160e+09, 1.54626175e+09, 1.54626190e+09,
       1.54626221e+09, 1.54626236e+09, 1.54626251e+09, 1.54626266e+09,
       1.54626281e+09, 1.54626311e+09, 1.54626326e+09, 1.54626341e+09,
       1.54626356e+09, 1.54626371e+09, 1.54626401e+09, 1.54626416e+09,
       1.54626430e+09, 1.54626445e+09, 1.54626460e+09, 1.54626490e+09,
       1.54626505e+09, 1.54626520e+09, 1.54626534e+09, 1.54626549e+09,
       1.54626579e+09, 1.54626594e+09, 1.54626609e+09, 1.54626624e+09,
       1.54626653e+09, 1.54626668e+09, 1.54626683e+09, 1.54626698e+09,
      

In [206]:
# compare these values to that below
in_data[ in_data['sensor_id'] == unique_sensor_ids[ 1 ] ].iloc[:20]

sensor_id sensor_namee     lat     lon     timestamp    p1    p2
0           7273       SDS011  60.002  17.846  1.546257e+09  3.43  1.56
175         7273       SDS011  60.002  17.846  1.546258e+09  3.78  1.55
44754       7273       SDS011  60.002  17.846  1.546258e+09  4.12  1.90
44833       7273       SDS011  60.002  17.846  1.546258e+09  3.45  1.75
42851       7273       SDS011  60.002  17.846  1.546258e+09  2.10  1.36
45041       7273       SDS011  60.002  17.846  1.546258e+09  1.45  1.16
43013       7273       SDS011  60.002  17.846  1.546258e+09  2.02  1.28
45230       7273       SDS011  60.002  17.846  1.546259e+09  1.78  1.36
43186       7273       SDS011  60.002  17.846  1.546259e+09  2.00  1.36
43267       7273       SDS011  60.002  17.846  1.546259e+09  2.45  1.42
43426       7273       SDS011  60.002  17.846  1.546259e+09  2.58  1.55
43345       7273       SDS011  60.002  17.846  1.546259e+09  2.58  1.55
43699       7273       SDS011  60.002  17.846  1.546259e+09  3.67  1.80
45593       7273       SDS011  60.002  17.846  1.546259e+09  3.67  1.80
43874       7273       SDS011  60.002  17.846  1.546260e+09  2.30  1.88
44049       7273       SDS011  60.002  17.846  1.546260e+09  2.80  1.84
44224       7273       SDS011  60.002  17.846  1.546260e+09  2.74  1.75
44401       7273       SDS011  60.002  17.846  1.546260e+09  3.00  1.80
44579       7273       SDS011  60.002  17.846  1.546260e+09  2.95  1.83
47741       7273       SDS011  60.002  17.846  1.546261e+09  2.46  1.75

#### now find out which index in the out array these times represent.

In [207]:
found_minimal_value

1546257442.0

In [208]:
# subtract the min value, so when we divide, we get multiples of this 
out_numpy_array_w_all_sensor_values = out_numpy_array_w_all_sensor_values - found_minimal_value


In [209]:
out_numpy_array_w_all_sensor_values

array([[ 7.92600000e+04,  7.92600000e+04, -1.54625744e+09, ...,
        -1.54625744e+09, -1.54625744e+09, -1.54625744e+09],
       [ 0.00000000e+00,  1.48000000e+02,  4.45000000e+02, ...,
        -1.54625744e+09, -1.54625744e+09, -1.54625744e+09],
       [-1.54625744e+09, -1.54625744e+09, -1.54625744e+09, ...,
        -1.54625744e+09, -1.54625744e+09, -1.54625744e+09],
       ...,
       [-1.54625744e+09, -1.54625744e+09, -1.54625744e+09, ...,
        -1.54625744e+09, -1.54625744e+09, -1.54625744e+09],
       [-1.54625744e+09, -1.54625744e+09, -1.54625744e+09, ...,
        -1.54625744e+09, -1.54625744e+09, -1.54625744e+09],
       [-1.54625744e+09, -1.54625744e+09, -1.54625744e+09, ...,
        -1.54625744e+09, -1.54625744e+09, -1.54625744e+09]])

In [210]:
out_numpy_array_w_all_sensor_values[0]

array([ 7.92600000e+04,  7.92600000e+04, -1.54625744e+09, -1.54625744e+09,
       -1.54625744e+09, -1.54625744e+09, -1.54625744e+09, -1.54625744e+09,
       -1.54625744e+09, -1.54625744e+09, -1.54625744e+09, -1.54625744e+09,
       -1.54625744e+09, -1.54625744e+09, -1.54625744e+09, -1.54625744e+09,
       -1.54625744e+09, -1.54625744e+09, -1.54625744e+09, -1.54625744e+09,
       -1.54625744e+09, -1.54625744e+09, -1.54625744e+09, -1.54625744e+09,
       -1.54625744e+09, -1.54625744e+09, -1.54625744e+09, -1.54625744e+09,
       -1.54625744e+09, -1.54625744e+09, -1.54625744e+09, -1.54625744e+09,
       -1.54625744e+09, -1.54625744e+09, -1.54625744e+09, -1.54625744e+09,
       -1.54625744e+09, -1.54625744e+09, -1.54625744e+09, -1.54625744e+09,
       -1.54625744e+09, -1.54625744e+09, -1.54625744e+09, -1.54625744e+09,
       -1.54625744e+09, -1.54625744e+09, -1.54625744e+09, -1.54625744e+09,
       -1.54625744e+09, -1.54625744e+09, -1.54625744e+09, -1.54625744e+09,
       -1.54625744e+09, -

In [211]:
out_numpy_array_w_all_sensor_values[1]

array([ 0.00000000e+00,  1.48000000e+02,  4.45000000e+02,  5.94000000e+02,
        7.42000000e+02,  8.91000000e+02,  1.04100000e+03,  1.34100000e+03,
        1.49000000e+03,  1.63800000e+03,  1.78700000e+03,  1.78700000e+03,
        1.93500000e+03,  1.93500000e+03,  2.23300000e+03,  2.38100000e+03,
        2.53000000e+03,  2.67800000e+03,  2.97500000e+03,  3.12400000e+03,
        3.27200000e+03,  3.42100000e+03,  3.56900000e+03,  3.86600000e+03,
        4.01500000e+03,  4.16300000e+03,  4.31200000e+03,  4.46000000e+03,
        4.76500000e+03,  4.91500000e+03,  5.06600000e+03,  5.21500000e+03,
        5.36600000e+03,  5.67100000e+03,  5.82200000e+03,  5.97000000e+03,
        6.11900000e+03,  6.26700000e+03,  6.56400000e+03,  6.71300000e+03,
        6.86100000e+03,  7.01200000e+03,  7.16000000e+03,  7.45700000e+03,
        7.60600000e+03,  7.75400000e+03,  7.90300000e+03,  8.05200000e+03,
        8.34800000e+03,  8.49700000e+03,  8.64600000e+03,  8.79500000e+03,
        9.09200000e+03,  

In [212]:
type( out_numpy_array_w_all_sensor_values[0][0] ) 

numpy.float64

In [213]:
# divide by the sensing period length in seconds, 
# to get the index of the item in the final array

In [214]:
out_numpy_array_w_all_sensor_values = out_numpy_array_w_all_sensor_values / sensing_period_lengths_in_seconds

In [215]:
out_numpy_array_w_all_sensor_values[1]

array([ 0.00000000e+00,  8.22222222e-01,  2.47222222e+00,  3.30000000e+00,
        4.12222222e+00,  4.95000000e+00,  5.78333333e+00,  7.45000000e+00,
        8.27777778e+00,  9.10000000e+00,  9.92777778e+00,  9.92777778e+00,
        1.07500000e+01,  1.07500000e+01,  1.24055556e+01,  1.32277778e+01,
        1.40555556e+01,  1.48777778e+01,  1.65277778e+01,  1.73555556e+01,
        1.81777778e+01,  1.90055556e+01,  1.98277778e+01,  2.14777778e+01,
        2.23055556e+01,  2.31277778e+01,  2.39555556e+01,  2.47777778e+01,
        2.64722222e+01,  2.73055556e+01,  2.81444444e+01,  2.89722222e+01,
        2.98111111e+01,  3.15055556e+01,  3.23444444e+01,  3.31666667e+01,
        3.39944444e+01,  3.48166667e+01,  3.64666667e+01,  3.72944444e+01,
        3.81166667e+01,  3.89555556e+01,  3.97777778e+01,  4.14277778e+01,
        4.22555556e+01,  4.30777778e+01,  4.39055556e+01,  4.47333333e+01,
        4.63777778e+01,  4.72055556e+01,  4.80333333e+01,  4.88611111e+01,
        5.05111111e+01,  

In [216]:
type( out_numpy_array_w_all_sensor_values[0][0] ) 

numpy.float64

In [217]:
# floor values, convert array to int, to get indicies :) 

In [218]:
out_numpy_array_w_all_sensor_values = out_numpy_array_w_all_sensor_values.astype( 'int64')

In [219]:
out_numpy_array_w_all_sensor_values[1]

array([       0,        0,        2,        3,        4,        4,
              5,        7,        8,        9,        9,        9,
             10,       10,       12,       13,       14,       14,
             16,       17,       18,       19,       19,       21,
             22,       23,       23,       24,       26,       27,
             28,       28,       29,       31,       32,       33,
             33,       34,       36,       37,       38,       38,
             39,       41,       42,       43,       43,       44,
             46,       47,       48,       48,       50,       51,
             52,       52,       53,       55,       56,       57,
             57,       58,       60,       61,       62,       62,
             63,       65,       66,       67,       67,       69,
             70,       71,       71,       72,       74,       75,
             76,       76,       77,       79,       80,       81,
             81,       82,       84,       85,       86,      

In [220]:
type( out_numpy_array_w_all_sensor_values[0][0] ) 

numpy.int64

#### get all values into an equal sizes array 

##### ie. use the length of the odd-sized array as an insertion point to the new array

In [221]:
out_numpy_array_w_all_sensor_values.shape

(205, 722)

In [222]:
for row in out_numpy_array_w_all_sensor_values:
    print( row )

[     440      440 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319
 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319
 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319
 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319
 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319
 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319
 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319
 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319
 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319
 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319
 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319
 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319
 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319
 -8590319 -8590319 -8590319 -8590319 -8590319 -8590

[-8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319
 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319
 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319
 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319
 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319
 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319
 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319
 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319
 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319
 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319
 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319
 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319
 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319 -8590319
 -8590319 -8590319 -8590319 -8590319 -8590319 -8590

### now try using the index array we got from the timestamps
##### to insert values in the the right norder. 

In [223]:
# test run - make 0-9 array
range10 = np.arange( 10 )
range10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [224]:
# make blank array
zeros10 = np.zeros( 10 )
zeros10

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [225]:
# - test making array using index 
range10[ [ 0,1,2,3,4 ] ]

array([0, 1, 2, 3, 4])

In [226]:
# - test making array using index 
test_index = np.array( [ 0, 1, 2, 3 ] )
test_index

array([0, 1, 2, 3])

In [227]:
type( test_index[0] )

numpy.int64

In [228]:
range10[ test_index ]

array([0, 1, 2, 3])

In [229]:
# combine indexing of input and output
zeros10[ np.array( [5,3,2,1,0] ) ] = range10[ np.array( [0,1,2,3,4] ) ]

In [230]:
zeros10

array([4., 3., 2., 1., 0., 0., 0., 0., 0., 0.])

In [235]:
#### see how long it wuold take to insert the values using loops

In [264]:
out_numpy_array_w_all_sensor_values_03 = np.ones( num_of__unique_sensor_ids * max_num_of_sensings_per_day )
out_numpy_array_w_all_sensor_values_03 = out_numpy_array_w_all_sensor_values_03*-1

In [265]:
out_numpy_array_w_all_sensor_values_03 = out_numpy_array_w_all_sensor_values_03.reshape( [ num_of__unique_sensor_ids, max_num_of_sensings_per_day ] )
out_numpy_array_w_all_sensor_values_03.shape

(205, 722)

In [266]:
type( out_numpy_array_w_all_sensor_values_03[0] ) 

numpy.ndarray

In [267]:
out_numpy_array_w_all_sensor_values_03

array([[-1., -1., -1., ..., -1., -1., -1.],
       [-1., -1., -1., ..., -1., -1., -1.],
       [-1., -1., -1., ..., -1., -1., -1.],
       ...,
       [-1., -1., -1., ..., -1., -1., -1.],
       [-1., -1., -1., ..., -1., -1., -1.],
       [-1., -1., -1., ..., -1., -1., -1.]])

In [268]:
out_numpy_array_w_all_sensor_values

array([[     440,      440, -8590319, ..., -8590319, -8590319, -8590319],
       [       0,        0,        2, ..., -8590319, -8590319, -8590319],
       [-8590319, -8590319, -8590319, ..., -8590319, -8590319, -8590319],
       ...,
       [-8590319, -8590319, -8590319, ..., -8590319, -8590319, -8590319],
       [-8590319, -8590319, -8590319, ..., -8590319, -8590319, -8590319],
       [-8590319, -8590319, -8590319, ..., -8590319, -8590319, -8590319]])

In [275]:
out_numpy_array_w_all_sensor_values[0]

array([     440,      440, -8590319, -8590319, -8590319, -8590319,
       -8590319, -8590319, -8590319, -8590319, -8590319, -8590319,
       -8590319, -8590319, -8590319, -8590319, -8590319, -8590319,
       -8590319, -8590319, -8590319, -8590319, -8590319, -8590319,
       -8590319, -8590319, -8590319, -8590319, -8590319, -8590319,
       -8590319, -8590319, -8590319, -8590319, -8590319, -8590319,
       -8590319, -8590319, -8590319, -8590319, -8590319, -8590319,
       -8590319, -8590319, -8590319, -8590319, -8590319, -8590319,
       -8590319, -8590319, -8590319, -8590319, -8590319, -8590319,
       -8590319, -8590319, -8590319, -8590319, -8590319, -8590319,
       -8590319, -8590319, -8590319, -8590319, -8590319, -8590319,
       -8590319, -8590319, -8590319, -8590319, -8590319, -8590319,
       -8590319, -8590319, -8590319, -8590319, -8590319, -8590319,
       -8590319, -8590319, -8590319, -8590319, -8590319, -8590319,
       -8590319, -8590319, -8590319, -8590319, -8590319, -8590

In [269]:
out_numpy_array_w_all_sensor_values[0]

array([     440,      440, -8590319, -8590319, -8590319, -8590319,
       -8590319, -8590319, -8590319, -8590319, -8590319, -8590319,
       -8590319, -8590319, -8590319, -8590319, -8590319, -8590319,
       -8590319, -8590319, -8590319, -8590319, -8590319, -8590319,
       -8590319, -8590319, -8590319, -8590319, -8590319, -8590319,
       -8590319, -8590319, -8590319, -8590319, -8590319, -8590319,
       -8590319, -8590319, -8590319, -8590319, -8590319, -8590319,
       -8590319, -8590319, -8590319, -8590319, -8590319, -8590319,
       -8590319, -8590319, -8590319, -8590319, -8590319, -8590319,
       -8590319, -8590319, -8590319, -8590319, -8590319, -8590319,
       -8590319, -8590319, -8590319, -8590319, -8590319, -8590319,
       -8590319, -8590319, -8590319, -8590319, -8590319, -8590319,
       -8590319, -8590319, -8590319, -8590319, -8590319, -8590319,
       -8590319, -8590319, -8590319, -8590319, -8590319, -8590319,
       -8590319, -8590319, -8590319, -8590319, -8590319, -8590

In [277]:
out_numpy_array_w_all_sensor_values[1]

array([       0,        0,        2,        3,        4,        4,
              5,        7,        8,        9,        9,        9,
             10,       10,       12,       13,       14,       14,
             16,       17,       18,       19,       19,       21,
             22,       23,       23,       24,       26,       27,
             28,       28,       29,       31,       32,       33,
             33,       34,       36,       37,       38,       38,
             39,       41,       42,       43,       43,       44,
             46,       47,       48,       48,       50,       51,
             52,       52,       53,       55,       56,       57,
             57,       58,       60,       61,       62,       62,
             63,       65,       66,       67,       67,       69,
             70,       71,       71,       72,       74,       75,
             76,       76,       77,       79,       80,       81,
             81,       82,       84,       85,       86,      

In [270]:
starttime = time.time()

# for each row ( y )
# for row_i in range( out_numpy_array_w_all_sensor_values_03.shape[0] ):
for row_i in range( 2 ):
    
    print("\n --- working on row "+str( row_i )+"/"+str( out_numpy_array_w_all_sensor_values.shape[0] )+" -- "+str( unique_sensor_ids[ row_i ]  ) )
    
    # for each column ( x )
    for col_i in range( out_numpy_array_w_all_sensor_values_03.shape[1] ):
        
        print("-- -- working on col #"+str( col_i)+" which has value "+str(0)+" and out_numpy_array_w_all_sensor_values out col i = "+str(  out_numpy_array_w_all_sensor_values[ row_i ][ col_i ] ) )
        
        curr_out_col_i = out_numpy_array_w_all_sensor_values[ row_i ][ col_i ]
        
        # curr_val = out_numpy_array_w_all_sensor_values_PART_TWO[ row_i ][  ]
        
        if curr_out_col_i < 0 or curr_out_col_i >  out_numpy_array_w_all_sensor_values.shape[1]:
            continue
        else : 
            out_numpy_array_w_all_sensor_values_03[ row_i ][ curr_out_col_i ] = out_numpy_array_w_all_sensor_values_PART_TWO[ row_i ][ col_i ]
        
# --- and when it's all over… 
print("\n\n >>>> and that all took "+str( time.time() - starttime ) )


 --- working on row 0/205 -- 5321
-- -- working on col #0 which has value 0 and out_numpy_array_w_all_sensor_values out col i = 440
-- -- working on col #1 which has value 0 and out_numpy_array_w_all_sensor_values out col i = 440
-- -- working on col #2 which has value 0 and out_numpy_array_w_all_sensor_values out col i = -8590319
-- -- working on col #3 which has value 0 and out_numpy_array_w_all_sensor_values out col i = -8590319
-- -- working on col #4 which has value 0 and out_numpy_array_w_all_sensor_values out col i = -8590319
-- -- working on col #5 which has value 0 and out_numpy_array_w_all_sensor_values out col i = -8590319
-- -- working on col #6 which has value 0 and out_numpy_array_w_all_sensor_values out col i = -8590319
-- -- working on col #7 which has value 0 and out_numpy_array_w_all_sensor_values out col i = -8590319
-- -- working on col #8 which has value 0 and out_numpy_array_w_all_sensor_values out col i = -8590319
-- -- working on col #9 which has value 0 and ou

In [271]:
out_numpy_array_w_all_sensor_values_03.shape

(205, 722)

In [276]:
out_numpy_array_w_all_sensor_values_03[0]

array([-1.  , -1.  , -1.  , -1.  , -1.  , -1.  , -1.  , -1.  , -1.  ,
       -1.  , -1.  , -1.  , -1.  , -1.  , -1.  , -1.  , -1.  , -1.  ,
       -1.  , -1.  , -1.  , -1.  , -1.  , -1.  , -1.  , -1.  , -1.  ,
       -1.  , -1.  , -1.  , -1.  , -1.  , -1.  , -1.  , -1.  , -1.  ,
       -1.  , -1.  , -1.  , -1.  , -1.  , -1.  , -1.  , -1.  , -1.  ,
       -1.  , -1.  , -1.  , -1.  , -1.  , -1.  , -1.  , -1.  , -1.  ,
       -1.  , -1.  , -1.  , -1.  , -1.  , -1.  , -1.  , -1.  , -1.  ,
       -1.  , -1.  , -1.  , -1.  , -1.  , -1.  , -1.  , -1.  , -1.  ,
       -1.  , -1.  , -1.  , -1.  , -1.  , -1.  , -1.  , -1.  , -1.  ,
       -1.  , -1.  , -1.  , -1.  , -1.  , -1.  , -1.  , -1.  , -1.  ,
       -1.  , -1.  , -1.  , -1.  , -1.  , -1.  , -1.  , -1.  , -1.  ,
       -1.  , -1.  , -1.  , -1.  , -1.  , -1.  , -1.  , -1.  , -1.  ,
       -1.  , -1.  , -1.  , -1.  , -1.  , -1.  , -1.  , -1.  , -1.  ,
       -1.  , -1.  , -1.  , -1.  , -1.  , -1.  , -1.  , -1.  , -1.  ,
       -1.  , -1.  ,

In [289]:
# debugging 
out_numpy_array_w_all_sensor_values[1][:17]

array([ 0,  0,  2,  3,  4,  4,  5,  7,  8,  9,  9,  9, 10, 10, 12, 13, 14])

In [290]:
# debugging 
in_data[ in_data['sensor_id'] == unique_sensor_ids[1] ][:17]

sensor_id sensor_namee     lat     lon     timestamp    p1    p2
0           7273       SDS011  60.002  17.846  1.546257e+09  3.43  1.56
175         7273       SDS011  60.002  17.846  1.546258e+09  3.78  1.55
44754       7273       SDS011  60.002  17.846  1.546258e+09  4.12  1.90
44833       7273       SDS011  60.002  17.846  1.546258e+09  3.45  1.75
42851       7273       SDS011  60.002  17.846  1.546258e+09  2.10  1.36
45041       7273       SDS011  60.002  17.846  1.546258e+09  1.45  1.16
43013       7273       SDS011  60.002  17.846  1.546258e+09  2.02  1.28
45230       7273       SDS011  60.002  17.846  1.546259e+09  1.78  1.36
43186       7273       SDS011  60.002  17.846  1.546259e+09  2.00  1.36
43267       7273       SDS011  60.002  17.846  1.546259e+09  2.45  1.42
43426       7273       SDS011  60.002  17.846  1.546259e+09  2.58  1.55
43345       7273       SDS011  60.002  17.846  1.546259e+09  2.58  1.55
43699       7273       SDS011  60.002  17.846  1.546259e+09  3.67  1.80
45593       7273       SDS011  60.002  17.846  1.546259e+09  3.67  1.80
43874       7273       SDS011  60.002  17.846  1.546260e+09  2.30  1.88
44049       7273       SDS011  60.002  17.846  1.546260e+09  2.80  1.84
44224       7273       SDS011  60.002  17.846  1.546260e+09  2.74  1.75

In [273]:
out_numpy_array_w_all_sensor_values_03[1]

array([  3.78,  -1.  ,   4.12,   3.45,   1.45,   2.02,  -1.  ,   1.78,
         2.  ,   2.58,   3.67,  -1.  ,   2.3 ,   2.8 ,   3.  ,  -1.  ,
         2.95,   2.46,   3.2 ,   2.14,  -1.  ,   2.35,   2.25,   2.04,
         2.11,  -1.  ,   2.25,   2.22,   3.43,   3.92,  -1.  ,   3.57,
         3.67,   3.78,   3.47,  -1.  ,   4.25,   3.95,   4.3 ,   3.68,
        -1.  ,   3.35,   3.54,   2.78,   3.18,  -1.  ,   3.8 ,   3.7 ,
         2.48,  -1.  ,   2.3 ,  24.2 ,  36.15,  56.58,  -1.  ,   4.9 ,
         9.7 ,   7.  ,   6.12,  -1.  ,  10.38,   6.96,   7.76,  28.13,
        -1.  ,  13.18,   4.42,   6.25,  -1.  ,  23.21, 455.  , 128.9 ,
        16.56,  -1.  ,  21.8 ,  11.36,  23.78,  22.02,  -1.  ,  14.3 ,
         8.06,   3.1 ,   4.08,  -1.  ,   2.15,   2.06,   3.8 ,  -1.  ,
         3.11,   3.6 ,   2.85,   2.37,  -1.  ,  -1.  ,  59.75, 157.77,
        77.23,  76.95,  -1.  ,  33.72,  42.24,   9.18,  -1.  ,  14.96,
        13.89,  38.6 ,  71.92,  -1.  ,  65.44,  31.08,   6.35,   3.88,
      

In [274]:
for row_ in out_numpy_array_w_all_sensor_values_03:
    print( row_ )

[-1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.
 -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.
 -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.
 -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.
 -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.
 -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.
 -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.
 -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.
 -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.
 -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.
 -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.
 -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.
 -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.
 -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.
 -1.  

[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1

[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1

 -1. -1.]
[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. 

[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1

sensor_id sensor_namee     lat     lon     timestamp    p1    p2
0           7273       SDS011  60.002  17.846  1.546257e+09  3.43  1.56
175         7273       SDS011  60.002  17.846  1.546258e+09  3.78  1.55
44754       7273       SDS011  60.002  17.846  1.546258e+09  4.12  1.90
44833       7273       SDS011  60.002  17.846  1.546258e+09  3.45  1.75
42851       7273       SDS011  60.002  17.846  1.546258e+09  2.10  1.36
45041       7273       SDS011  60.002  17.846  1.546258e+09  1.45  1.16
43013       7273       SDS011  60.002  17.846  1.546258e+09  2.02  1.28
45230       7273       SDS011  60.002  17.846  1.546259e+09  1.78  1.36
43186       7273       SDS011  60.002  17.846  1.546259e+09  2.00  1.36
43267       7273       SDS011  60.002  17.846  1.546259e+09  2.45  1.42
43426       7273       SDS011  60.002  17.846  1.546259e+09  2.58  1.55
43345       7273       SDS011  60.002  17.846  1.546259e+09  2.58  1.55
43699       7273       SDS011  60.002  17.846  1.546259e+09  3.67  1.80
45593       7273       SDS011  60.002  17.846  1.546259e+09  3.67  1.80
43874       7273       SDS011  60.002  17.846  1.546260e+09  2.30  1.88
44049       7273       SDS011  60.002  17.846  1.546260e+09  2.80  1.84
44224       7273       SDS011  60.002  17.846  1.546260e+09  2.74  1.75
44401       7273       SDS011  60.002  17.846  1.546260e+09  3.00  1.80
44579       7273       SDS011  60.002  17.846  1.546260e+09  2.95  1.83
47741       7273       SDS011  60.002  17.846  1.546261e+09  2.46  1.75
47825       7273       SDS011  60.002  17.846  1.546261e+09  3.20  1.60
47910       7273       SDS011  60.002  17.846  1.546261e+09  3.28  1.50
47987       7273       SDS011  60.002  17.846  1.546261e+09  2.14  1.46
46035       7273       SDS011  60.002  17.846  1.546261e+09  2.35  1.42
46124       7273       SDS011  60.002  17.846  1.546261e+09  2.25  1.28
46199       7273       SDS011  60.002  17.846  1.546262e+09  2.50  1.36
48357       7273       SDS011  60.002  17.846  1.546262e+09  2.04  1.45
46374       7273       SDS011  60.002  17.846  1.546262e+09  2.11  1.40
48517       7273       SDS011  60.002  17.846  1.546262e+09  2.25  1.62
46578       7273       SDS011  60.002  17.846  1.546262e+09  2.22  1.64
...          ...          ...     ...     ...           ...   ...   ...
36287       7273       SDS011  60.002  17.846  1.546382e+09  1.64  1.28
36463       7273       SDS011  60.002  17.846  1.546382e+09  1.60  1.20
36639       7273       SDS011  60.002  17.846  1.546382e+09  2.43  1.32
36814       7273       SDS011  60.002  17.846  1.546382e+09  3.85  1.52
36987       7273       SDS011  60.002  17.846  1.546382e+09  4.04  1.35
37162       7273       SDS011  60.002  17.846  1.546383e+09  2.55  1.38
37340       7273       SDS011  60.002  17.846  1.546383e+09  2.88  1.45
37520       7273       SDS011  60.002  17.846  1.546383e+09  3.55  1.45
37697       7273       SDS011  60.002  17.846  1.546383e+09  4.05  1.35
37874       7273       SDS011  60.002  17.846  1.546383e+09  3.56  1.35
38050       7273       SDS011  60.002  17.846  1.546384e+09  3.62  1.25
38225       7273       SDS011  60.002  17.846  1.546384e+09  3.12  1.18
38398       7273       SDS011  60.002  17.846  1.546384e+09  2.93  1.34
38575       7273       SDS011  60.002  17.846  1.546384e+09  3.57  1.30
41889       7273       SDS011  60.002  17.846  1.546384e+09  3.18  1.14
39642       7273       SDS011  60.002  17.846  1.546385e+09  4.22  1.28
42066       7273       SDS011  60.002  17.846  1.546385e+09  3.28  1.23
39829       7273       SDS011  60.002  17.846  1.546385e+09  3.64  1.45
39915       7273       SDS011  60.002  17.846  1.546385e+09  3.66  1.56
39989       7273       SDS011  60.002  17.846  1.546385e+09  5.98  1.65
42429       7273       SDS011  60.002  17.846  1.546385e+09  4.80  1.36
40172       7273       SDS011  60.002  17.846  1.546386e+09  3.68  1.18
40257       7273       SDS011  60.002  17.846  1.546386e+09  3.73  1.08
40347       7273       SDS011  60.002  17.846  