In [4]:
import pandas as pd
import numpy as np
import time

In [5]:
# parameters

# start_time = "2018-12-31 21:58:42"
end_time = "2019-01-01 11:58:42"
# generate this please
start_time = "?????"

time_frequency_for_periods__for_basic_data = "5T"
num_of_time_periods___for_basic_data = 24*20 # 24 hrs * 12 x 5 mins in each hour

# when generating time periods 
sampling_frequency = "3T"



# --- data urls 

curr_url = "????"
nordic_midnight_24_hrs_data__url = "/Users/miska/Documents/open_something/luftdaten/luftdaten_code/luftdaten__make_tabular_data__from_db_data/ld_NYE_midnight_24hrs_nordics_all_data_01.csv"

# set the current data source 
curr_url =nordic_midnight_24_hrs_data__url

In [6]:
# try convert the timestamp in the data, to epoch

in_data = pd.read_csv( curr_url )
in_data.shape

(127109, 7)

In [7]:
unique_sensor_ids = in_data['sensor_id'].unique()
unique_sensor_ids.shape

(205,)

In [8]:
unique_sensor_ids

array([ 7273,  7275,  7277,  7406,  7428,  7469,  7597,  8683,  9411,
        9436,  9743,  9797, 10216, 10250, 10281, 10430, 10647, 10721,
       10723, 10803, 10823, 10825, 10827, 10843, 10914, 10922, 10924,
       10926, 11002, 11004, 11006, 11058, 11232, 11374, 11376, 11378,
       11380, 11384, 11404, 11445, 11543, 11546, 11550, 11552, 11661,
       11663, 11763, 11765, 11767, 11769, 11771, 11773, 12120, 12124,
       12129, 12131, 12133, 12135, 12137, 12141, 12381, 12383, 12385,
       12387, 12389, 12391, 12393, 12663, 12673, 12679, 12687, 12691,
       12693, 12861, 12990, 12994, 13000, 13010, 13012, 13018, 13020,
       13307, 13419, 13421, 13423, 13425, 13428, 13441, 13443, 13475,
       13477, 13483, 13762, 14133, 14209, 14264, 14276, 14278, 14282,
       14290, 14292, 14294, 14296, 14722, 14797, 14799, 14801, 14803,
       14807, 14809, 14811, 14813, 14817, 14835, 14837, 14975, 15067,
       15069, 15071, 15073, 15549, 15551, 15561, 15837, 16147, 16149,
       16151, 16153,

In [9]:
sensor_7273_unique_rows = in_data[ in_data['sensor_id'] == 7273 ]
sensor_7273_unique_rows.shape

(716, 7)

In [10]:
sensor_7273_unique_rows

sensor_id sensor_namee     lat     lon            timestamp    p1  \
0            7273       SDS011  60.002  17.846  2018-12-31 11:57:22  3.43   
175          7273       SDS011  60.002  17.846  2018-12-31 11:59:50  3.78   
346          7273       SDS011  60.002  17.846  2019-01-01 12:04:31  3.60   
522          7273       SDS011  60.002  17.846  2019-01-01 12:07:00  2.47   
700          7273       SDS011  60.002  17.846  2019-01-01 12:09:28  1.97   
873          7273       SDS011  60.002  17.846  2019-01-01 12:11:57  1.87   
1047         7273       SDS011  60.002  17.846  2019-01-01 12:16:54  2.60   
1225         7273       SDS011  60.002  17.846  2019-01-01 12:19:25  1.98   
1404         7273       SDS011  60.002  17.846  2019-01-01 12:21:53  2.24   
1581         7273       SDS011  60.002  17.846  2019-01-01 12:24:22  3.32   
1758         7273       SDS011  60.002  17.846  2019-01-01 12:26:50  2.52   
1938         7273       SDS011  60.002  17.846  2019-01-01 12:31:47  1.72   
2110         7273       SDS011  60.002  17.846  2019-01-01 12:34:16  2.14   
2288         7273       SDS011  60.002  17.846  2019-01-01 12:36:47  2.54   
2463         7273       SDS011  60.002  17.846  2019-01-01 12:39:16  2.18   
2642         7273       SDS011  60.002  17.846  2019-01-01 12:41:44  1.95   
2817         7273       SDS011  60.002  17.846  2019-01-01 12:46:41  1.78   
2992         7273       SDS011  60.002  17.846  2019-01-01 12:49:10  1.48   
3187         7273       SDS011  60.002  17.846  2019-01-01 12:54:07  1.88   
3347         7273       SDS011  60.002  17.846  2019-01-01 12:56:35  1.97   
3525         7273       SDS011  60.002  17.846  2019-01-01 13:01:35  1.63   
3707         7273       SDS011  60.002  17.846  2019-01-01 13:04:07  1.46   
3884         7273       SDS011  60.002  17.846  2019-01-01 13:06:35  2.44   
4063         7273       SDS011  60.002  17.846  2019-01-01 13:09:04  2.98   
4241         7273       SDS011  60.002  17.846  2019-01-01 13:11:33  2.48   
4419         7273       SDS011  60.002  17.846  2019-01-01 13:16:40  1.64   
4597         7273       SDS011  60.002  17.846  2019-01-01 13:19:09  2.25   
4774         7273       SDS011  60.002  17.846  2019-01-01 13:21:44  2.48   
4953         7273       SDS011  60.002  17.846  2019-01-01 13:24:31  2.27   
5131         7273       SDS011  60.002  17.846  2019-01-01 13:27:00  1.37   
...           ...          ...     ...     ...                  ...   ...   
121946       7273       SDS011  60.002  17.846  2019-01-01 10:32:47  3.85   
122128       7273       SDS011  60.002  17.846  2019-01-01 10:37:44  3.83   
122297       7273       SDS011  60.002  17.846  2019-01-01 10:40:16  3.63   
122470       7273       SDS011  60.002  17.846  2019-01-01 10:42:44  3.43   
122647       7273       SDS011  60.002  17.846  2019-01-01 10:45:13  3.32   
122824       7273       SDS011  60.002  17.846  2019-01-01 10:47:44  4.00   
122998       7273       SDS011  60.002  17.846  2019-01-01 10:52:44  2.97   
123174       7273       SDS011  60.002  17.846  2019-01-01 10:55:12  3.32   
123351       7273       SDS011  60.002  17.846  2019-01-01 10:57:41  4.37   
123518       7273       SDS011  60.002  17.846  2019-01-01 11:00:09  4.05   
123703       7273       SDS011  60.002  17.846  2019-01-01 11:02:38  4.30   
123881       7273       SDS011  60.002  17.846  2019-01-01 11:07:35  3.50   
124063       7273       SDS011  60.002  17.846  2019-01-01 11:10:03  2.42   
124236       7273       SDS011  60.002  17.846  2019-01-01 11:12:32  2.60   
124356       7273       SDS011  60.002  17.846  2019-01-01 11:15:00  4.60   
124539       7273       SDS011  60.002  17.846  2019-01-01 11:22:26  3.60   
124776       7273       SDS011  60.002  17.846  2019-01-01 11:19:57  4.16   
125095       7273       SDS011  60.002  17.846  2019-01-01 11:24:54  3.46   
125198       7273       SDS011  60.002  17.846  2019-01-01 11:27:23  2.76   
125296       7273       SDS011  60.002  17.846  2019-01-01 11:29:51  2.88   
1254

In [11]:
sensor_7273_unique_rows[ sensor_7273_unique_rows['p1'] == 3.45 ]

sensor_id sensor_namee     lat     lon            timestamp    p1    p2
44833       7273       SDS011  60.002  17.846  2018-12-31 12:07:16  3.45  1.75

In [12]:
sensor_7273_unique_rows__sorted_by_time = sensor_7273_unique_rows.sort_values( by=['timestamp'] )

In [30]:
%time sensor_7273_unique_rows__sorted_by_time = sensor_7273_unique_rows.sort_values( by=['timestamp'] )

CPU times: user 1.89 ms, sys: 892 µs, total: 2.78 ms
Wall time: 1.99 ms


In [21]:
np.arange( 10 )

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
one = np.array( np.arange(10) )

In [27]:
one[0]

0

In [28]:
type( one[0] )

numpy.int64

In [29]:
one.reshape( 12 )

ValueError: cannot reshape array of size 10 into shape (12,)

#### checking out changing the size of arrays - eg here with pad(ding)

In [32]:
np.pad( one, (0,4), 'edge')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 9, 9, 9])

In [34]:
np.pad( one, (0,4), 'constant', constant_values=(-1))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, -1, -1, -1, -1])

#### trying to insert list items in numpy arrays

In [37]:
list_ = range( 10 )

In [38]:
list_

range(0, 10)

In [39]:
np_array = np.array( list_ ) 

In [40]:
type( np_array[0] ) 

numpy.int64

In [41]:
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

sensor_id sensor_namee     lat     lon            timestamp    p1  \
0            7273       SDS011  60.002  17.846  2018-12-31 11:57:22  3.43   
175          7273       SDS011  60.002  17.846  2018-12-31 11:59:50  3.78   
346          7273       SDS011  60.002  17.846  2019-01-01 12:04:31  3.60   
522          7273       SDS011  60.002  17.846  2019-01-01 12:07:00  2.47   
700          7273       SDS011  60.002  17.846  2019-01-01 12:09:28  1.97   
873          7273       SDS011  60.002  17.846  2019-01-01 12:11:57  1.87   
1047         7273       SDS011  60.002  17.846  2019-01-01 12:16:54  2.60   
1225         7273       SDS011  60.002  17.846  2019-01-01 12:19:25  1.98   
1404         7273       SDS011  60.002  17.846  2019-01-01 12:21:53  2.24   
1581         7273       SDS011  60.002  17.846  2019-01-01 12:24:22  3.32   
1758         7273       SDS011  60.002  17.846  2019-01-01 12:26:50  2.52   
1938         7273       SDS011  60.002  17.846  2019-01-01 12:31:47  1.72   
2110         7273       SDS011  60.002  17.846  2019-01-01 12:34:16  2.14   
2288         7273       SDS011  60.002  17.846  2019-01-01 12:36:47  2.54   
2463         7273       SDS011  60.002  17.846  2019-01-01 12:39:16  2.18   
2642         7273       SDS011  60.002  17.846  2019-01-01 12:41:44  1.95   
2817         7273       SDS011  60.002  17.846  2019-01-01 12:46:41  1.78   
2992         7273       SDS011  60.002  17.846  2019-01-01 12:49:10  1.48   
3187         7273       SDS011  60.002  17.846  2019-01-01 12:54:07  1.88   
3347         7273       SDS011  60.002  17.846  2019-01-01 12:56:35  1.97   
3525         7273       SDS011  60.002  17.846  2019-01-01 13:01:35  1.63   
3707         7273       SDS011  60.002  17.846  2019-01-01 13:04:07  1.46   
3884         7273       SDS011  60.002  17.846  2019-01-01 13:06:35  2.44   
4063         7273       SDS011  60.002  17.846  2019-01-01 13:09:04  2.98   
4241         7273       SDS011  60.002  17.846  2019-01-01 13:11:33  2.48   
4419         7273       SDS011  60.002  17.846  2019-01-01 13:16:40  1.64   
4597         7273       SDS011  60.002  17.846  2019-01-01 13:19:09  2.25   
4774         7273       SDS011  60.002  17.846  2019-01-01 13:21:44  2.48   
4953         7273       SDS011  60.002  17.846  2019-01-01 13:24:31  2.27   
5131         7273       SDS011  60.002  17.846  2019-01-01 13:27:00  1.37   
...           ...          ...     ...     ...                  ...   ...   
121946       7273       SDS011  60.002  17.846  2019-01-01 10:32:47  3.85   
122128       7273       SDS011  60.002  17.846  2019-01-01 10:37:44  3.83   
122297       7273       SDS011  60.002  17.846  2019-01-01 10:40:16  3.63   
122470       7273       SDS011  60.002  17.846  2019-01-01 10:42:44  3.43   
122647       7273       SDS011  60.002  17.846  2019-01-01 10:45:13  3.32   
122824       7273       SDS011  60.002  17.846  2019-01-01 10:47:44  4.00   
122998       7273       SDS011  60.002  17.846  2019-01-01 10:52:44  2.97   
123174       7273       SDS011  60.002  17.846  2019-01-01 10:55:12  3.32   
123351       7273       SDS011  60.002  17.846  2019-01-01 10:57:41  4.37   
123518       7273       SDS011  60.002  17.846  2019-01-01 11:00:09  4.05   
123703       7273       SDS011  60.002  17.846  2019-01-01 11:02:38  4.30   
123881       7273       SDS011  60.002  17.846  2019-01-01 11:07:35  3.50   
124063       7273       SDS011  60.002  17.846  2019-01-01 11:10:03  2.42   
124236       7273       SDS011  60.002  17.846  2019-01-01 11:12:32  2.60   
124356       7273       SDS011  60.002  17.846  2019-01-01 11:15:00  4.60   
124539       7273       SDS011  60.002  17.846  2019-01-01 11:22:26  3.60   
124776       7273       SDS011  60.002  17.846  2019-01-01 11:19:57  4.16   
125095       7273       SDS011  60.002  17.846  2019-01-01 11:24:54  3.46   
125198       7273       SDS011  60.002  17.846  2019-01-01 11:27:23  2.76   
125296       7273       SDS011  60.002  17.846  2019-01-01 11:29:51  2.88   
1254

#### trying to make a multi-dimensional np_array

In [85]:
unique_sensor_ids = in_data['sensor_id'].unique().shape[0]
num_of_rows.shape[0]

205

In [86]:
unique_sensor_ids

205

In [87]:
num_of_items_per_row = ( 20 * 24 ) # number of 3 minute periods in an hour * 24 hour 
num_of_items_per_row

480

In [88]:
array_w_slots_for_all_sensors_and_time_periods_in_the_day = np.zeros( unique_sensor_ids * num_of_items_per_row )

In [89]:
array_w_slots_for_all_sensors_and_time_periods_in_the_day = array_w_slots_for_all_sensors_and_time_periods_in_the_day.reshape( [ unique_sensor_ids, num_of_items_per_row  ])

In [90]:
array_w_slots_for_all_sensors_and_time_periods_in_the_day.shape

(205, 480)

In [92]:
array_w_slots_for_all_sensors_and_time_periods_in_the_day[0].shape

(480,)

In [67]:
#### now try fetch all the data from different sensors ids… 

In [68]:
# first, let's see how long it takes 

In [96]:
starttime = time.time()

# get all unique sensor ids 
unique_sensor_ids = in_data['sensor_id'].unique()

# out list of sensor id data
out_list_of_sensor_ids = []

# array lengths 
array_lengths = []

for curr_sensor_id in unique_sensor_ids:
        
        curr_sensor_data = in_data[ in_data['sensor_id'] == curr_sensor_id ]
        
        curr_array_length = curr_sensor_data.shape[0]
        array_lengths.append( curr_array_length )
        
        print("\n -- working on sensor_id "+str( curr_sensor_id)+" - which has a length of "+str( curr_array_length ) )
        

print("\n ----- and that all took "+str( time.time() - starttime )+" seconds ")
    



 -- working on sensor_id 7273 - which has a length of 716

 -- working on sensor_id 7275 - which has a length of 692

 -- working on sensor_id 7277 - which has a length of 721

 -- working on sensor_id 7406 - which has a length of 720

 -- working on sensor_id 7428 - which has a length of 721

 -- working on sensor_id 7469 - which has a length of 700

 -- working on sensor_id 7597 - which has a length of 721

 -- working on sensor_id 8683 - which has a length of 721

 -- working on sensor_id 9411 - which has a length of 650

 -- working on sensor_id 9436 - which has a length of 722

 -- working on sensor_id 9743 - which has a length of 498

 -- working on sensor_id 9797 - which has a length of 721

 -- working on sensor_id 10216 - which has a length of 721

 -- working on sensor_id 10250 - which has a length of 719

 -- working on sensor_id 10281 - which has a length of 720

 -- working on sensor_id 10430 - which has a length of 721

 -- working on sensor_id 10647 - which has a length

In [98]:
array_lengths

[716,
 692,
 721,
 720,
 721,
 700,
 721,
 721,
 650,
 722,
 498,
 721,
 721,
 719,
 720,
 721,
 721,
 721,
 711,
 721,
 720,
 722,
 700,
 722,
 721,
 721,
 721,
 721,
 722,
 721,
 720,
 721,
 720,
 716,
 721,
 722,
 699,
 719,
 720,
 721,
 720,
 720,
 224,
 357,
 717,
 720,
 722,
 721,
 720,
 722,
 721,
 424,
 721,
 722,
 722,
 721,
 397,
 721,
 721,
 721,
 721,
 706,
 659,
 722,
 721,
 718,
 721,
 717,
 720,
 234,
 691,
 721,
 709,
 719,
 708,
 720,
 720,
 713,
 706,
 720,
 640,
 632,
 721,
 721,
 509,
 681,
 721,
 720,
 722,
 720,
 721,
 720,
 398,
 698,
 721,
 721,
 721,
 709,
 721,
 554,
 721,
 717,
 710,
 577,
 721,
 721,
 703,
 722,
 721,
 720,
 719,
 721,
 721,
 644,
 720,
 720,
 721,
 721,
 692,
 719,
 676,
 721,
 720,
 721,
 640,
 705,
 722,
 346,
 720,
 722,
 696,
 721,
 721,
 336,
 721,
 720,
 721,
 720,
 721,
 458,
 721,
 721,
 721,
 720,
 719,
 721,
 719,
 694,
 722,
 721,
 721,
 721,
 719,
 721,
 722,
 722,
 721,
 722,
 715,
 721,
 721,
 720,
 721,
 241,
 369,
 721,
 721

In [109]:
max_num_of_sensings_per_day = np.max( array_lengths ) 

In [110]:
max_array_length

722

In [111]:
np.array( in_data[ in_data['sensor_id'] == unique_sensor_ids[0] ]['p1'] ) 

array([3.4300e+00, 3.7800e+00, 3.6000e+00, 2.4700e+00, 1.9700e+00,
       1.8700e+00, 2.6000e+00, 1.9800e+00, 2.2400e+00, 3.3200e+00,
       2.5200e+00, 1.7200e+00, 2.1400e+00, 2.5400e+00, 2.1800e+00,
       1.9500e+00, 1.7800e+00, 1.4800e+00, 1.8800e+00, 1.9700e+00,
       1.6300e+00, 1.4600e+00, 2.4400e+00, 2.9800e+00, 2.4800e+00,
       1.6400e+00, 2.2500e+00, 2.4800e+00, 2.2700e+00, 1.3700e+00,
       1.2000e+00, 1.2500e+00, 1.5200e+00, 2.1200e+00, 1.6500e+00,
       1.1400e+00, 1.3500e+00, 1.6500e+00, 1.5500e+00, 1.6800e+00,
       2.2200e+00, 1.4200e+00, 1.5400e+00, 1.3800e+00, 1.2300e+00,
       1.2300e+00, 2.1800e+00, 1.6200e+00, 1.9200e+00, 1.8600e+00,
       1.6100e+00, 9.1000e-01, 1.1800e+00, 1.9200e+00, 1.6400e+00,
       1.0000e+00, 1.2000e+00, 1.4000e+00, 1.5800e+00, 1.7500e+00,
       1.7500e+00, 6.0000e-01, 9.9000e-01, 1.0800e+00, 7.0000e-01,
       6.5000e-01, 1.3800e+00, 1.7500e+00, 1.1200e+00, 6.8000e-01,
       9.9000e-01, 6.4000e-01, 6.4000e-01, 7.5000e-01, 8.5000e

#### now try the same with the real numpy out_array … 

In [116]:
# -- first make an array to fit the out values

# prepare variables

sensing_period_lengths_in_min = 3

sensing_periods_in_a_day = int( 60/sensing_period_lengths_in_min )
sensing_periods_in_a_day




20

In [117]:
type( max_num_of_sensings_per_day ) 

numpy.int64

In [118]:
type( sensing_periods_in_a_day )

int

In [134]:
# get all unique sensor ids 
unique_sensor_ids = in_data['sensor_id'].unique()
num_of__unique_sensor_ids = unique_sensor_ids.shape[0]

In [135]:
out_numpy_array_w_all_sensor_values = np.zeros( num_of__unique_sensor_ids * max_num_of_sensings_per_day )

In [136]:
out_numpy_array_w_all_sensor_values = out_numpy_array_w_all_sensor_values.reshape( [ num_of__unique_sensor_ids, max_num_of_sensings_per_day ] )

In [137]:
out_numpy_array_w_all_sensor_values.shape

(205, 722)

In [138]:
out_numpy_array_w_all_sensor_values

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [139]:
starttime = time.time()

for curr_sensor_id_index in range( unique_sensor_ids.shape[0] ) :
        
        curr_sensor_data = in_data[ in_data['sensor_id'] == unique_sensor_ids[ curr_sensor_id_index ] ]['p1']
        
        curr_sensor_data_length = curr_sensor_data.shape[0]
        
        print("\n -- working on row "+str( curr_sensor_id)+"/"+str( unique_sensor_ids.shape[0] )+" sensor_id "+str( unique_sensor_ids[ curr_sensor_id_index ] )+" - which has a length of "+str( curr_sensor_data_length ) )
        
        # assign the data into the numpy array 
        out_numpy_array_w_all_sensor_values[ curr_sensor_id_index ][ 0 : curr_sensor_data_length ] = curr_sensor_data
        

print("\n ----- and that all took "+str( time.time() - starttime )+" seconds ")
    


 -- working on row 5321/205 sensor_id 7273 - which has a length of 716

 -- working on row 5321/205 sensor_id 7275 - which has a length of 692

 -- working on row 5321/205 sensor_id 7277 - which has a length of 721

 -- working on row 5321/205 sensor_id 7406 - which has a length of 720

 -- working on row 5321/205 sensor_id 7428 - which has a length of 721

 -- working on row 5321/205 sensor_id 7469 - which has a length of 700

 -- working on row 5321/205 sensor_id 7597 - which has a length of 721

 -- working on row 5321/205 sensor_id 8683 - which has a length of 721

 -- working on row 5321/205 sensor_id 9411 - which has a length of 650

 -- working on row 5321/205 sensor_id 9436 - which has a length of 722

 -- working on row 5321/205 sensor_id 9743 - which has a length of 498

 -- working on row 5321/205 sensor_id 9797 - which has a length of 721

 -- working on row 5321/205 sensor_id 10216 - which has a length of 721

 -- working on row 5321/205 sensor_id 10250 - which has a leng

In [140]:
out_numpy_array_w_all_sensor_values[0]

array([3.4300e+00, 3.7800e+00, 3.6000e+00, 2.4700e+00, 1.9700e+00,
       1.8700e+00, 2.6000e+00, 1.9800e+00, 2.2400e+00, 3.3200e+00,
       2.5200e+00, 1.7200e+00, 2.1400e+00, 2.5400e+00, 2.1800e+00,
       1.9500e+00, 1.7800e+00, 1.4800e+00, 1.8800e+00, 1.9700e+00,
       1.6300e+00, 1.4600e+00, 2.4400e+00, 2.9800e+00, 2.4800e+00,
       1.6400e+00, 2.2500e+00, 2.4800e+00, 2.2700e+00, 1.3700e+00,
       1.2000e+00, 1.2500e+00, 1.5200e+00, 2.1200e+00, 1.6500e+00,
       1.1400e+00, 1.3500e+00, 1.6500e+00, 1.5500e+00, 1.6800e+00,
       2.2200e+00, 1.4200e+00, 1.5400e+00, 1.3800e+00, 1.2300e+00,
       1.2300e+00, 2.1800e+00, 1.6200e+00, 1.9200e+00, 1.8600e+00,
       1.6100e+00, 9.1000e-01, 1.1800e+00, 1.9200e+00, 1.6400e+00,
       1.0000e+00, 1.2000e+00, 1.4000e+00, 1.5800e+00, 1.7500e+00,
       1.7500e+00, 6.0000e-01, 9.9000e-01, 1.0800e+00, 7.0000e-01,
       6.5000e-01, 1.3800e+00, 1.7500e+00, 1.1200e+00, 6.8000e-01,
       9.9000e-01, 6.4000e-01, 6.4000e-01, 7.5000e-01, 8.5000e